export const ROUTES = {
  home: "/",
  hrmsHome: "/hrms",
  hrmsPricing: "/hrms/pricing",
  hrmsPricingPurchase: "/hrms/pricing/purchase",
  checkoutBase: "/checkout",
  customerAccess: "/account/access",
  dashboard: "/dashboard",
  dashboardBilling: "/dashboard/billing",
  paymentSuccess: "/payment/success",
  paymentFailed: "/payment/failed",
  hrmsContact: "/hrms/contact-us",
  roiCalculator: "/hrms/roi-calculator",
  coreHR: "/hrms/products/core-hr",
  attendance: "/hrms/products/attendance",
  attendanceManagement: "/hrms/products/attendance-management",
  payroll: "/hrms/products/payroll",
  leaveManagement: "/hrms/products/leave-management",
  mobileAppLanding: "/hrms/products/mobile-app-landing",
  recruitment: "/hrms/products/recruitment-ats",
  performance: "/hrms/products/performance-management",
  assetManagement: "/asset-management",
  assetManagementHome: "/asset-management",
  assetManagementAbout: "/asset-management/about-us",
  expenseManagement: "/hrms/products/expense-management",
  documentGeneration: "/hrms/products/document-generation",
  visitorManagement: "/hrms/products/document-generation",
  exitManagement: "/hrms/products/exit-management",
  employeeSelfService: "/hrms/products/employee-self-service",
  analytics: "/hrms/hr-analytics",
  automation: "/hrms/hr-automation",
  reports: "/hrms/hr-reports",
  security: "/hrms/hrms-security",
  workforce: "/hrms/products/workforce-management",
  industrySolutions: "/hrms/industry-solutions",
  integrations: "/hrms/integrations",
  businessApps: "/hrms/integrations/hr-business-applications",
  accounting: "/hrms/integrations/accounting",
  devicesApi: "/hrms/integrations/devices-api",
  bulkEmail: "/bulk-email",
  bulkEmailAbout: "/bulk-email/about-us",
  bulkEmailCampaigns: "/bulk-email/campaigns",
  bulkEmailTemplates: "/bulk-email/templates",
  bulkEmailContacts: "/bulk-email/contacts",
  bulkEmailAnalytics: "/bulk-email/analytics",
  bulkEmailAutomation: "/bulk-email/automation",
  bulkEmailScheduling: "/bulk-email/scheduling",
  bulkEmailSmtp: "/bulk-email/smtp",
  bulkEmailHrCommunication: "/bulk-email/hr-communication",
  bulkEmailMarketing: "/bulk-email/marketing",
  bulkEmailEducation: "/bulk-email/education",
  bulkEmailContact: "/bulk-email/contact-us",
  bulkEmailPricing: "/bulk-email/pricing",
  bulkEmailBookDemo: "/bulk-email/company/book-demo",
  bulkEmailLearn: "/bulk-email/resources/learn",
  bulkEmailBlog: "/bulk-email/resources/blog",
  bulkEmailFaq: "/bulk-email/resources/faq",
  bulkEmailAssetManagement: "/asset-management/overview",
  bulkEmailAssetDashboard: "/asset-management/dashboard",
  bulkEmailAssetTracking: "/asset-management/tracking",
  bulkEmailAssetQrCode: "/asset-management/qr-code",
  bulkEmailAssetMaintenance: "/asset-management/maintenance",
  bulkEmailAssetReports: "/asset-management/reports",
  learn: "/resources/learn",
  hrmsLearn: "/hrms/resources/learn",
  video: "/resources/video",
  hrmsVideo: "/hrms/resources/video",
  complianceGuides: "/resources/compliance-guides",
  hrmsComplianceGuides: "/hrms/resources/compliance-guides",
  blog: "/resources/blog",
  hrmsBlog: "/hrms/resources/blog",
  bulkEmailBlogPost: "/bulk-email/resources/blog/:slug",
  hrmsBlogPost: "/hrms/resources/blog/:slug",
  assetManagementBlogPost: "/asset-management/resources/blog/:slug",
  blogPost: "/resources/blog/:slug",
  faq: "/resources/faq",
  hrmsFaq: "/hrms/resources/faq",
  bulkEmailFaq: "/bulk-email/resources/faq",
  supportResources: "/hrms/resources/support",
  pricing: "/pricing",
  assetManagementLearn: "/asset-management/resources/learn",
  assetManagementGuide: "/asset-management/asset-management-guide",
  assetManagementBlog: "/asset-management/resources/blog",
  assetManagementFaq: "/asset-management/resources/faq",
  assetManagementContact: "/asset-management/contact-us",
  assetManagementPricing: "/asset-management/pricing",
  assetManagementBookDemo: "/asset-management/company/book-demo",
  about: "/hrms/company/about-us",
  whyAltroz: "/hrms/company/why-altroz",
  customers: "/hrms/company/customers",
  testimonials: "/hrms/company/testimonials",
  partner: "/hrms/company/partner-with-us",
  careers: "/hrms/company/careers",
  contact: "/hrms/contact-us",
  support: "/hrms/company/help-center",
  bookDemo: "/hrms/company/book-demo",
  bulkEmailBroadcast: "/bulk-email/broadcast",
  privacyPolicy: "/legal/privacy-policy",
  termsAndConditions: "/legal/terms-and-conditions",
  cookiePolicy: "/legal/cookie-policy",
  sitemap: "/sitemap",
};

export const ROUTE_ALIASES = {
  "/about-us": ROUTES.about,
  "/altroz-hr": ROUTES.hrmsHome,
  "/hrms-home": ROUTES.hrmsHome,
  "/pricing": ROUTES.hrmsPricing,
  "/pricing/purchase": ROUTES.hrmsPricingPurchase,
  "/login": ROUTES.customerAccess,
  "/register": ROUTES.customerAccess,
  "/company/about-us": ROUTES.about,
  "/company/contact-us": ROUTES.hrmsContact,
  "/company/customers": ROUTES.customers,
  "/company/testimonials": ROUTES.testimonials,
  "/company/partner-with-us": ROUTES.partner,
  "/company/careers": ROUTES.careers,
  "/company/help-center": ROUTES.support,
  "/company/book-demo": ROUTES.bookDemo,
  "/roi-calculator": ROUTES.roiCalculator,
  "/products/core-hr": ROUTES.coreHR,
  "/products/attendance": ROUTES.attendanceManagement,
  "/products/attendance-management": ROUTES.attendanceManagement,
  "/attendance-management": ROUTES.attendanceManagement,
  "/products/payroll": ROUTES.payroll,
  "/products/leave-management": ROUTES.leaveManagement,
  "/products/mobile-app-landing": ROUTES.mobileAppLanding,
  "/products/recruitment-ats": ROUTES.recruitment,
  "/products/recruitment": ROUTES.recruitment,
  "/products/performance-management": ROUTES.performance,
  "/products/asset-management": ROUTES.assetManagementHome,
  "/products/expense-management": ROUTES.expenseManagement,
  "/products/document-generation": ROUTES.documentGeneration,
  "/products/exit-management": ROUTES.exitManagement,
  "/products/employee-self-service": ROUTES.employeeSelfService,
  "/products/workforce-management": ROUTES.workforce,
  "/hr-analytics": ROUTES.analytics,
  "/hr-automation": ROUTES.automation,
  "/hr-reports": ROUTES.reports,
  "/hrms-security": ROUTES.security,
  "/industry-solutions": ROUTES.industrySolutions,
  "/integrations": ROUTES.integrations,
  "/integrations/hr-business-applications": ROUTES.businessApps,
  "/integrations/accounting": ROUTES.accounting,
  "/integrations/devices-api": ROUTES.devicesApi,
  "/attendance": ROUTES.attendanceManagement,
  "/customers": ROUTES.customers,
  "/company/why-altoz": ROUTES.whyAltroz,
  "/why-altroz": ROUTES.whyAltroz,
  "/careers": ROUTES.careers,
  "/integrations/asset-management": ROUTES.assetManagementHome,
  "/about-asset-management": ROUTES.assetManagementAbout,
  "/asset_management/company/book-demo": ROUTES.assetManagementBookDemo,
  "/bulk-email/asset-management": ROUTES.bulkEmailAssetManagement,
  "/bulk-email/asset-management/dashboard": ROUTES.bulkEmailAssetDashboard,
  "/bulk-email/asset-management/tracking": ROUTES.bulkEmailAssetTracking,
  "/bulk-email/asset-management/qr-code": ROUTES.bulkEmailAssetQrCode,
  "/bulk-email/asset-management/maintenance": ROUTES.bulkEmailAssetMaintenance,
  "/bulk-email/asset-management/reports": ROUTES.bulkEmailAssetReports,
  "/integrations/business-apps": ROUTES.businessApps,
  "/learn": ROUTES.hrmsLearn,
  "/resources/learn": ROUTES.hrmsLearn,
  "/resources/learning": ROUTES.hrmsLearn,
  "/resources/video": ROUTES.hrmsVideo,
  "/resources/compliance-guides": ROUTES.hrmsComplianceGuides,
  "/compliance-guides": ROUTES.hrmsComplianceGuides,
  "/resources/blog": ROUTES.hrmsBlog,
  "/blog": ROUTES.hrmsBlog,
  "/resources/blog/what-is-hrms": `${ROUTES.hrmsBlog}/what-is-hrms`,
  "/blog/what-is-hrms": `${ROUTES.hrmsBlog}/what-is-hrms`,
  "/resources/faq": ROUTES.hrmsFaq,
  "/faq": ROUTES.hrmsFaq,
  "/resources/support": ROUTES.supportResources,
  "/partner-with-us": ROUTES.partner,
  "/email-broadcast": ROUTES.bulkEmailBroadcast,
  "/about-bulk-email": ROUTES.bulkEmailAbout,
  "/bulk-email/email-broadcast": ROUTES.bulkEmailBroadcast,
  "/bulk-email/contacts": ROUTES.bulkEmailContact,
  "/bulk-email/campaigns": ROUTES.bulkEmail,
  "/bulk_email/company/book-demo": ROUTES.bulkEmailBookDemo,
  "/mobile-app-landing": ROUTES.mobileAppLanding,
  "/mobile-app": ROUTES.mobileAppLanding,
  "/products/visitor-management": ROUTES.documentGeneration,
  "/company/support": ROUTES.support,
  "/help-center": ROUTES.support,
  "/solutions/industry": ROUTES.industrySolutions,
  "/solutions/workforce-management": ROUTES.workforce,
};

export const INTERNAL_ROUTE_SET = new Set([
  ...Object.values(ROUTES),
  ...Object.keys(ROUTE_ALIASES),
]);

export function normalizePath(pathname = "/") {
  const withoutQuery = pathname.split("?")[0] ?? "/";
  const withoutHash = withoutQuery.split("#")[0] ?? "/";
  const trimmed = withoutHash.replace(/\/+$/, "");
  return trimmed === "" ? "/" : trimmed;
}

export function normalizeHref(href = "") {
  if (!href) {
    return "";
  }

  if (href.startsWith("#")) {
    return "";
  }

  return normalizePath(href);
}

export function isExternalHref(href = "") {
  return /^(https?:|mailto:|tel:|whatsapp:)/i.test(href);
}

export function isInternalHref(href = "") {
  if (!href || isExternalHref(href)) {
    return false;
  }

  return href.startsWith("/") || href.startsWith("#");
}

export function getRedirectTarget(pathname = "/") {
  const normalized = normalizePath(pathname);
  return ROUTE_ALIASES[normalized] ?? null;
}
