const included = "included";
const notIncluded = "notIncluded";
const limited = "limited";
const optional = "optional";
const addOn = "addon";

const row = (title, basic, professional, premium, note) => ({
  title,
  basic,
  professional,
  premium,
  note,
});

export const hrmsPricingFeatureSections = [
  {
    sectionKey: "pricing-features-employee-management",
    heading: "Employee Management",
    description: "Core employee records, profile tools and organization setup.",
    rows: [
      row("Employee Database", included, included, included),
      row("Employee Profile Management", included, included, included),
      row("Employee Master Records", included, included, included),
      row("Employee Directory", included, included, included),
      row("Department Management", included, included, included),
      row("Designation Management", included, included, included),
      row("Branch Management", included, included, included),
      row("Employee Category Management", included, included, included),
      row("Employee Lifecycle Tracking", notIncluded, included, included),
      row("Employee History", included, included, included),
      row("Employee Document Management", included, included, included),
      row("Employee Search", included, included, included),
      row("Employee Status Management", included, included, included),
      row("Employee Information Dashboard", included, notIncluded, included),
    ],
  },
  {
    sectionKey: "pricing-features-attendance",
    heading: "Attendance",
    description: "Attendance capture, shift control and attendance reporting.",
    rows: [
      row("Biometric Attendance Integration", included, included, included),
      row("GPS Based Attendance", notIncluded, included, included),
      row("Geo Location Attendance", included, included, included),
      row("Geo Fencing", optional, included, included, "Add-on on Basic"),
      row("Shift Management", notIncluded, notIncluded, included),
      row("Attendance Dashboard", included, included, included),
      row("Attendance Regularization", notIncluded, included, included),
      row("Missing Punch Management", notIncluded, included, included),
      row("Late Mark Management", included, included, included),
      row("Overtime Tracking", included, included, included),
      row("Attendance Summary", included, included, included),
      row("Daily Attendance Report", included, included, included),
      row("Monthly Attendance Report", included, included, included),
      row("Branch Wise Attendance", included, included, included),
      row("Department Wise Attendance", included, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-leave",
    heading: "Leave",
    description: "Leave workflows, calendar visibility and leave analytics.",
    rows: [
      row("Leave Dashboard", included, included, included),
      row("Leave Request", included, included, included),
      row("Leave Approval Workflow", included, included, included),
      row("Multi-Level Approval", notIncluded, included, included),
      row("Leave Balance Tracking", included, included, included),
      row("Leave Transaction History", included, included, included),
      row("Leave Calendar", included, included, included),
      row("Leave Types Configuration", included, included, included),
      row("Holiday Management", included, included, included),
      row("Pending Leave Tracking", included, included, included),
      row("Leave Reports", included, included, included),
      row("Department Wise Leave Reports", included, included, included),
      row("Leave Analytics", included, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-recruitment",
    heading: "Recruitment",
    description: "Applicant flow and recruiting coverage for the Premium plan.",
    rows: [
      row("Position Management", notIncluded, notIncluded, included),
      row("Vacancy Management", notIncluded, notIncluded, included),
      row("Job Requisition", notIncluded, notIncluded, included),
      row("Applicant Management", notIncluded, notIncluded, included),
      row("Applicant Applications", notIncluded, notIncluded, included),
      row("Interview Scheduling", notIncluded, notIncluded, included),
      row("Interview Tracking", notIncluded, notIncluded, included),
      row("Offer Management", notIncluded, notIncluded, included),
      row("Recruitment Dashboard", notIncluded, notIncluded, included),
      row("Recruitment Reports", notIncluded, notIncluded, included),
    ],
  },
  {
    sectionKey: "pricing-features-documents",
    heading: "Documents",
    description: "Offer letters, templates, employee documents and document control.",
    rows: [
      row("Appointment Letter", notIncluded, included, included),
      row("Offer Letter", notIncluded, included, included),
      row("Joining Letter", notIncluded, included, included),
      row("PDF Document Generation", notIncluded, included, included),
      row("Document Templates", notIncluded, included, included),
      row("Employee Document Storage", notIncluded, included, included),
      row("Document Version Control", notIncluded, notIncluded, included),
      row("Document Download", notIncluded, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-payroll",
    heading: "Payroll",
    description: "Payroll processing, salary rules, reports and payroll analytics.",
    rows: [
      row("Payroll Dashboard", notIncluded, included, included),
      row("Payroll Processing", notIncluded, included, included),
      row("Salary Computation", notIncluded, included, included),
      row("Salary Processing", notIncluded, included, included),
      row("Payroll Settings", notIncluded, included, included),
      row("Compensation Templates", notIncluded, limited, included),
      row("Advance Salary Management", notIncluded, included, included),
      row("Salary Slip Generation", notIncluded, included, included),
      row("Salary History", notIncluded, notIncluded, included),
      row("Payroll Reports", notIncluded, included, included),
      row("Salary Reports", notIncluded, included, included),
      row("Payroll Summary", notIncluded, included, included),
      row("Payroll Analytics", notIncluded, included, included),
      row("Salary Advance Summary", notIncluded, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-compliance",
    heading: "Compliance",
    description: "Statutory settings and compliance reporting.",
    rows: [
      row("PF", notIncluded, included, included),
      row("ESI", notIncluded, included, included),
      row("PT", notIncluded, included, included),
      row("LWF", notIncluded, included, included),
      row("Tax Configuration", notIncluded, included, included),
      row("UAN Management", notIncluded, included, included),
      row("PF Reports", notIncluded, included, included),
      row("ESI Reports", notIncluded, included, included),
      row("PT Reports", notIncluded, included, included),
      row("Compliance Reports", notIncluded, notIncluded, included),
    ],
  },
  {
    sectionKey: "pricing-features-asset-management",
    heading: "Asset Management",
    description: "Asset allocation, tracking, maintenance and reporting.",
    rows: [
      row("Asset Dashboard", notIncluded, included, included),
      row("Asset Registration", notIncluded, included, included),
      row("Asset Allocation", notIncluded, included, included),
      row("Asset Hand Over", notIncluded, included, included),
      row("Asset Status Management", notIncluded, included, included),
      row("Asset Category Management", notIncluded, included, included),
      row("Asset Type Management", notIncluded, included, included),
      row("Asset Maintenance", notIncluded, included, included),
      row("Warranty Tracking", notIncluded, included, included),
      row("Asset Depreciation", notIncluded, included, included),
      row("Asset Utilization Tracking", notIncluded, included, included),
      row("Asset Reports", notIncluded, included, included),
      row("Asset History", notIncluded, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-performance",
    heading: "Performance",
    description: "Performance dashboards and employee performance tracking.",
    rows: [
      row("Performance Dashboard", notIncluded, included, included),
      row("Employee Performance Tracking", notIncluded, included, included),
      row("Performance Reports", notIncluded, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-team-actions",
    heading: "Team Actions",
    description: "Operational employee actions and engagement-related workflows.",
    rows: [
      row("Company Announcements", included, included, included),
      row("Employee Notifications", included, included, included),
      row("Employee Transfer", included, included, included),
      row("Employee Promotion", included, included, included),
      row("Employee Resignation", included, included, included),
      row("Employee Termination", included, included, included),
      row("Employee Reimbursement", included, notIncluded, included),
      row("Event Management", included, included, included),
      row("Holiday Management", included, included, included),
      row("Awards & Recognition", notIncluded, notIncluded, included),
    ],
  },
  {
    sectionKey: "pricing-features-reports",
    heading: "Reports",
    description: "Export-ready reports for people, payroll, attendance and assets.",
    rows: [
      row("Employee Reports", included, included, included),
      row("Employee Salary Reports", notIncluded, included, included),
      row("Attendance Reports", included, included, included),
      row("Leave Reports", included, included, included),
      row("Payroll Reports", notIncluded, included, included),
      row("PF Reports", notIncluded, included, included),
      row("ESI Reports", notIncluded, included, included),
      row("Professional Tax Reports", notIncluded, included, included),
      row("LWF Reports", notIncluded, included, included),
      row("Asset Reports", notIncluded, notIncluded, included),
      row("Excel Export", included, included, included),
      row("PDF Export", included, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-administration",
    heading: "Administration",
    description: "Organization setup, access control and system governance.",
    rows: [
      row("Role Management", included, included, included),
      row("User Management", included, included, included),
      row("User Employee Mapping", included, included, included),
      row("Multi-Level Approval", included, included, included),
      row("Organization Management", included, included, included),
      row("Company Configuration", included, included, included),
      row("Branch Configuration", included, included, included),
      row("Department Configuration", included, included, included),
      row("Notification Settings", included, included, included),
      row("Leave Type Configuration", included, included, included),
      row("Rule Engine", included, included, included),
    ],
  },
  {
    sectionKey: "pricing-features-add-ons",
    eyebrow: "Add On",
    heading: "Add On",
    description:
      "Optional capabilities that can be attached to any of the three plans when your team needs extra coverage.",
    rows: [
      row("Geo Tracking", addOn, addOn, addOn),
      row("Mobile App", addOn, addOn, addOn),
      row("API Integration", addOn, addOn, addOn),
      row("WhatsApp Integration", addOn, addOn, addOn),
      row("Biometric Device", addOn, addOn, addOn),
      row("Custom Development", addOn, addOn, addOn),
    ],
  },
];
